### ISSUE TITLE
Schema.md should be proper YAML, and fit with Github Jekyll engine: lowercase attributes and links

### ISSUE THREAD

**Issue by raphaelfournier** [polifonia-project/rulebook#14]
Some links format seems to not be availbable (such as [link](website)).

**Comment by enridaga** [comment]
In fd64c19 the main change is that the schema elements became lowercase -- I'll update the issue title to reflect that. Thanks for updating the existing components in https://github.com/polifonia-project/external-components

**Comment by raphaelfournier** [comment]
Apparently, it's even stricter than what I thought (but I don't find a source for that): spaces are not allowed, it's recommended to have hyphens ('-') or underscores ('_'). So "work Package" should become: work-package. 
Capital P was a vim mistake ;-)
